version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  redis:
    image: "redis:latest"
